# Generated by Django 2.2.7 on 2020-09-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('subject', models.CharField(choices=[('SMQA', 'Software Metrics and Quality Assurance'), ('CD', 'Compiler Design'), ('ES', 'Embedded System')], max_length=4)),
                ('year', models.CharField(choices=[('FE', 'First Year'), ('SE', 'Second Year'), ('TE', 'Third Year'), ('BE', 'Fourth Year')], max_length=2)),
                ('unit', models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V')], max_length=4)),
            ],
        ),
    ]
