# Generated by Django 2.2.7 on 2020-09-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='year',
            field=models.CharField(choices=[('BE', 'BE')], max_length=2),
        ),
    ]
