# Generated by Django 2.2.7 on 2020-09-16 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20200916_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(choices=[('ISE I', 'ISE I'), ('ISE II', 'ISE II'), ('ISE III', 'ISE III'), ('ISE IV', 'ISE IV'), ('ISE V', 'ISE V')], max_length=10)),
                ('test_created', models.DateTimeField(auto_now=True, verbose_name='Test Created on')),
                ('test_date', models.DateTimeField(verbose_name='Test Conducted on')),
                ('test_conducted', models.CharField(choices=[('T', 'T'), ('F', 'F'), ('D', 'D')], default=2, max_length=1)),
                ('test_duration', models.DurationField()),
                ('test_marks', models.IntegerField(default=10)),
                ('test_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.QuestionBank')),
            ],
        ),
    ]
