# Generated by Django 2.1.4 on 2020-09-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('profession', models.CharField(choices=[('S', 'Student'), ('P', 'Professor'), ('A', 'Admin')], max_length=1)),
                ('acc_status', models.BooleanField()),
                ('id_card', models.FileField(upload_to='')),
            ],
        ),
    ]
